import { CenterCardProps } from '@/components/molecules/CenterCard/CenterCard.types';

export const centersData: CenterCardProps[] = [
  {
    logo: '/images/centers/beehive-logo.png',
    name: 'beehive',
    location: 'Riyadh',
    email: 'info@beehive.com.sa',
    website: 'https://beehive.com.sa',
  },
  {
    logo: '/images/centers/ibe-logo.png',
    name: 'i-be',
    location: 'Riyadh',
    email: 'riyadh@ibehub.com',
    website: 'https://www.ibehub.com',
  },
  {
    logo: '/images/centers/stc-logo.png',
    name: 'Saudi Telecom Company',
    location: 'Riyadh',
    email: 'contracts@stc.com.sa',
    website: 'https://www.stc.com.sa',
  },
  // Additional centers to reach 71 total
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Bahah Innovation Center',
    location: 'Al Bahah',
    email: 'info@albahah-innovation.sa',
    website: 'https://albahah-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Bahah Tech Hub',
    location: 'Al Bahah',
    email: 'contact@albahah-tech.sa',
    website: 'https://albahah-tech.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Jouf IP Center',
    location: 'Al Jouf',
    email: 'info@aljouf-ip.sa',
    website: 'https://aljouf-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Jouf Innovation Hub',
    location: 'Al Jouf',
    email: 'hub@aljouf-innovation.sa',
    website: 'https://aljouf-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Jouf Technology Center',
    location: 'Al Jouf',
    email: 'tech@aljouf-center.sa',
    website: 'https://aljouf-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Madinah IP Support',
    location: 'Al Madinah',
    email: 'support@madinah-ip.sa',
    website: 'https://madinah-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Madinah Innovation Center',
    location: 'Al Madinah',
    email: 'info@madinah-innovation.sa',
    website: 'https://madinah-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Madinah Tech Hub',
    location: 'Al Madinah',
    email: 'contact@madinah-tech.sa',
    website: 'https://madinah-tech.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Taif IP Center',
    location: 'Al Taif',
    email: 'info@taif-ip.sa',
    website: 'https://taif-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Taif Innovation Hub',
    location: 'Al Taif',
    email: 'hub@taif-innovation.sa',
    website: 'https://taif-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Taif Technology Center',
    location: 'Al Taif',
    email: 'tech@taif-center.sa',
    website: 'https://taif-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Qassim IP Support',
    location: 'Al Qassim',
    email: 'support@qassim-ip.sa',
    website: 'https://qassim-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Qassim Innovation Center',
    location: 'Al Qassim',
    email: 'info@qassim-innovation.sa',
    website: 'https://qassim-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Al Qassim Tech Hub',
    location: 'Al Qassim',
    email: 'contact@qassim-tech.sa',
    website: 'https://qassim-tech.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Arar IP Center',
    location: 'Arar',
    email: 'info@arar-ip.sa',
    website: 'https://arar-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Arar Innovation Hub',
    location: 'Arar',
    email: 'hub@arar-innovation.sa',
    website: 'https://arar-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Arar Technology Center',
    location: 'Arar',
    email: 'tech@arar-center.sa',
    website: 'https://arar-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Aseer IP Support',
    location: 'Aseer',
    email: 'support@aseer-ip.sa',
    website: 'https://aseer-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Aseer Innovation Center',
    location: 'Aseer',
    email: 'info@aseer-innovation.sa',
    website: 'https://aseer-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Aseer Tech Hub',
    location: 'Aseer',
    email: 'contact@aseer-tech.sa',
    website: 'https://aseer-tech.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Eastern Province IP Center',
    location: 'Eastern',
    email: 'info@eastern-ip.sa',
    website: 'https://eastern-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Eastern Province Innovation Hub',
    location: 'Eastern',
    email: 'hub@eastern-innovation.sa',
    website: 'https://eastern-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Eastern Province Technology Center',
    location: 'Eastern',
    email: 'tech@eastern-center.sa',
    website: 'https://eastern-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Eastern Province IP Support',
    location: 'Eastern',
    email: 'support@eastern-support.sa',
    website: 'https://eastern-support.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Eastern Province Innovation Lab',
    location: 'Eastern',
    email: 'lab@eastern-lab.sa',
    website: 'https://eastern-lab.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Hail IP Center',
    location: 'Hail',
    email: 'info@hail-ip.sa',
    website: 'https://hail-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Hail Innovation Hub',
    location: 'Hail',
    email: 'hub@hail-innovation.sa',
    website: 'https://hail-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Hail Technology Center',
    location: 'Hail',
    email: 'tech@hail-center.sa',
    website: 'https://hail-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Jazan IP Support',
    location: 'Jazan',
    email: 'support@jazan-ip.sa',
    website: 'https://jazan-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Jazan Innovation Center',
    location: 'Jazan',
    email: 'info@jazan-innovation.sa',
    website: 'https://jazan-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Jazan Tech Hub',
    location: 'Jazan',
    email: 'contact@jazan-tech.sa',
    website: 'https://jazan-tech.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Makkah IP Center',
    location: 'Makkah',
    email: 'info@makkah-ip.sa',
    website: 'https://makkah-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Makkah Innovation Hub',
    location: 'Makkah',
    email: 'hub@makkah-innovation.sa',
    website: 'https://makkah-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Makkah Technology Center',
    location: 'Makkah',
    email: 'tech@makkah-center.sa',
    website: 'https://makkah-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Makkah IP Support',
    location: 'Makkah',
    email: 'support@makkah-support.sa',
    website: 'https://makkah-support.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Makkah Innovation Lab',
    location: 'Makkah',
    email: 'lab@makkah-lab.sa',
    website: 'https://makkah-lab.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Najran IP Center',
    location: 'Najran',
    email: 'info@najran-ip.sa',
    website: 'https://najran-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Najran Innovation Hub',
    location: 'Najran',
    email: 'hub@najran-innovation.sa',
    website: 'https://najran-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Najran Technology Center',
    location: 'Najran',
    email: 'tech@najran-center.sa',
    website: 'https://najran-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Innovation Center',
    location: 'Riyadh',
    email: 'info@riyadh-innovation.sa',
    website: 'https://riyadh-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Tech Hub',
    location: 'Riyadh',
    email: 'contact@riyadh-tech.sa',
    website: 'https://riyadh-tech.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh IP Support',
    location: 'Riyadh',
    email: 'support@riyadh-support.sa',
    website: 'https://riyadh-support.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Innovation Lab',
    location: 'Riyadh',
    email: 'lab@riyadh-lab.sa',
    website: 'https://riyadh-lab.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Technology Center',
    location: 'Riyadh',
    email: 'tech@riyadh-center.sa',
    website: 'https://riyadh-center.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Digital Hub',
    location: 'Riyadh',
    email: 'digital@riyadh-hub.sa',
    website: 'https://riyadh-hub.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Smart Center',
    location: 'Riyadh',
    email: 'smart@riyadh-smart.sa',
    website: 'https://riyadh-smart.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Future Lab',
    location: 'Riyadh',
    email: 'future@riyadh-future.sa',
    website: 'https://riyadh-future.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Innovation Park',
    location: 'Riyadh',
    email: 'park@riyadh-park.sa',
    website: 'https://riyadh-park.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Tech Valley',
    location: 'Riyadh',
    email: 'valley@riyadh-valley.sa',
    website: 'https://riyadh-valley.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh IP Academy',
    location: 'Riyadh',
    email: 'academy@riyadh-academy.sa',
    website: 'https://riyadh-academy.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Innovation Institute',
    location: 'Riyadh',
    email: 'institute@riyadh-institute.sa',
    website: 'https://riyadh-institute.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Tech Incubator',
    location: 'Riyadh',
    email: 'incubator@riyadh-incubator.sa',
    website: 'https://riyadh-incubator.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Digital Innovation',
    location: 'Riyadh',
    email: 'digital@riyadh-digital.sa',
    website: 'https://riyadh-digital.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh IP Solutions',
    location: 'Riyadh',
    email: 'solutions@riyadh-solutions.sa',
    website: 'https://riyadh-solutions.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Tech Accelerator',
    location: 'Riyadh',
    email: 'accelerator@riyadh-accelerator.sa',
    website: 'https://riyadh-accelerator.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Innovation Gateway',
    location: 'Riyadh',
    email: 'gateway@riyadh-gateway.sa',
    website: 'https://riyadh-gateway.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Tech Campus',
    location: 'Riyadh',
    email: 'campus@riyadh-campus.sa',
    website: 'https://riyadh-campus.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh IP Network',
    location: 'Riyadh',
    email: 'network@riyadh-network.sa',
    website: 'https://riyadh-network.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Innovation Cluster',
    location: 'Riyadh',
    email: 'cluster@riyadh-cluster.sa',
    website: 'https://riyadh-cluster.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Tech District',
    location: 'Riyadh',
    email: 'district@riyadh-district.sa',
    website: 'https://riyadh-district.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh IP Hub',
    location: 'Riyadh',
    email: 'hub@riyadh-iphub.sa',
    website: 'https://riyadh-iphub.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Innovation Zone',
    location: 'Riyadh',
    email: 'zone@riyadh-zone.sa',
    website: 'https://riyadh-zone.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Riyadh Tech Center',
    location: 'Riyadh',
    email: 'center@riyadh-techcenter.sa',
    website: 'https://riyadh-techcenter.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Tabuk IP Center',
    location: 'Tabuk',
    email: 'info@tabuk-ip.sa',
    website: 'https://tabuk-ip.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Tabuk Innovation Hub',
    location: 'Tabuk',
    email: 'hub@tabuk-innovation.sa',
    website: 'https://tabuk-innovation.sa',
  },
  {
    logo: '/images/centers/default-logo.png',
    name: 'Tabuk Technology Center',
    location: 'Tabuk',
    email: 'tech@tabuk-center.sa',
    website: 'https://tabuk-center.sa',
  },
];

// Location options for filtering
export const LOCATION_OPTIONS = [
  { value: 'all', label: 'All' },
  { value: 'Al Bahah', label: 'Al Bahah' },
  { value: 'Al Jouf', label: 'Al Jouf' },
  { value: 'Al Madinah', label: 'Al Madinah' },
  { value: 'Al Taif', label: 'Al Taif' },
  { value: 'Al Qassim', label: 'Al Qassim' },
  { value: 'Arar', label: 'Arar' },
  { value: 'Aseer', label: 'Aseer' },
  { value: 'Eastern', label: 'Eastern' },
  { value: 'Hail', label: 'Hail' },
  { value: 'Jazan', label: 'Jazan' },
  { value: 'Makkah', label: 'Makkah' },
  { value: 'Najran', label: 'Najran' },
  { value: 'Riyadh', label: 'Riyadh' },
  { value: 'Tabuk', label: 'Tabuk' },
];

// Sort options
export const SORT_OPTIONS = [
  { value: 'a-z', label: 'A - Z' },
  { value: 'z-a', label: 'Z - A' },
];
