import { TrainingProgram } from './TrainingProgramsSection.types';

export const MOCK_TRAINING_PROGRAMS: TrainingProgram[] = [
  {
    id: '1',
    title: 'Using data as an IP asset',
    date: '10.12.2024',
    time: '11:00 AM',
    category: 'Copyrights',
    duration: '3 hours',
    location: 'SAIP office',
    host: 'Umm Al-Qura University',
    fees: 'Free',
    registerHref: '#',
  },
  {
    id: '2',
    title: 'Using data as an IP asset',
    date: '10.12.2024',
    time: '11:00 AM',
    category: 'Copyrights',
    duration: '3 hours',
    location: 'SAIP office',
    host: 'Umm Al-Qura University',
    fees: 'Free',
    registerHref: '#',
  },
  {
    id: '3',
    title: 'Using data as an IP asset',
    date: '10.12.2024',
    time: '11:00 AM',
    category: 'Copyrights',
    duration: '3 hours',
    location: 'SAIP office',
    host: 'Umm Al-Qura University',
    fees: 'Free',
    registerHref: '#',
  },
  {
    id: '4',
    title: 'Using data as an IP asset',
    date: '10.12.2024',
    time: '11:00 AM',
    category: 'Copyrights',
    duration: '3 hours',
    location: 'SAIP office',
    host: 'Umm Al-Qura University',
    fees: 'Free',
    registerHref: '#',
  },
  {
    id: '5',
    title: 'Using data as an IP asset',
    date: '10.12.2024',
    time: '11:00 AM',
    category: 'Copyrights',
    duration: '3 hours',
    location: 'SAIP office',
    host: 'Umm Al-Qura University',
    fees: 'Free',
    registerHref: '#',
  },
  {
    id: '6',
    title: 'Using data as an IP asset',
    date: '10.12.2024',
    time: '11:00 AM',
    category: 'Copyrights',
    duration: '3 hours',
    location: 'SAIP office',
    host: 'Umm Al-Qura University',
    fees: 'Free',
    registerHref: '#',
  },
];
