import { cva } from 'class-variance-authority';

export const slider = cva([
  'absolute',
  'cursor-pointer',
  'top-0',
  'left-0',
  'right-0',
  'bottom-0',
  'bg-white',
  'border',
  'border-black',
  'peer-checked:border-transparent',
  'rounded-full',
  'transition-all',
  'before:content-[""]',
  'before:absolute',
  'before:left-1',
  'before:top-1',
  'before:bg-black',
  'before:w-4',
  'before:h-4',
  'before:rounded-full',
  'before:transition-all',
  'peer-checked:bg-button-background-primary-default',
  'peer-checked:before:bg-white',
  'peer-checked:before:border-none',
  'peer-checked:before:translate-x-6',
  'peer-disabled:opacity-50',
]);
